### ISSUE TITLE
Question: scenario variables for eglot

### ISSUE THREAD

**Issue by mgrojo** [brownts/dotemacs-ada#2]
This is just a question.

In the ada_language_server repository there is the following example for setting scenario variables for lsp-mode:

```elisp
((ada-mode .
  ((eval . (lsp-register-custom-settings
      '(("ada.scenarioVariables.BINUTILS_SRC_DIR" project-binutils-dir)
        ("ada.scenarioVariables.BUILD_TYPE" project-build-type "Release"))))
   (lsp-ada-project-file . "/home/username/project/project.gpr"))
  ))
```

Do you know how it would be the equivalent for eglot? It's information that would be useful to have, either here or in the ada_language_server repo.

**Comment by mgrojo** [comment]
I think I've found the way looking at the eglot manual, but there is a problem, and I don't know whose is the fault, because both eglot and lsp-mode behave equally. When there is a problem in the project, all that you get in flymake is this:
```
    1   0 warning  l-d---b  Project Problems
```
This is a warning because I'm using a very simple setup for testing (the [tutorial in ada_language_server](https://github.com/AdaCore/ada_language_server/wiki/Getting-Started)), but with my project it's an error.

In VS Code you get a second line explaining the project problems, but without that in Emacs, I'm being unable to debug the problem and fix my setup.

Any help wold be appreciated.

**Comment by brownts** [comment]
The lack of additional detail appears to be a deficiency in both Eglot and lsp-mode.  I looked at the [Diagnostic](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic) coming from the server and the information you see in VSCode is what is considered "related information".  It's not part of the diagnostic message itself (which just contains "Project Problems"), but is captured in these separate pieces of [DiagnosticRelatedInformation](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticRelatedInformation).

Each LSP client communicates to the server their [PublishDiagnosticsClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#publishDiagnosticsClientCapabilities).  Looking at this configuration in Eglot, it indicates that it doesn't support diagnostic "related information" [here](https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/eglot.el#L1004).  Therefore, its just not supported by Eglot at this point in time.  You could log an issue on the mailing list if you like, asking them to add this capability.

lsp-mode on the other hand, advertises that it does support diagnostic "related information" [here](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L3777).  Unfortunately, it appears the lsp-mode Flymake [back-end](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-diagnostics.el#L287) (and even the FlyCheck back-end) just doesn't do anything with that additional information.  An issue could be logged on the lsp-mode Github page if desired.

Typically what I've been doing in this situation is just going to the project file.  If you've configured `gpr-ts-mode` like this example configuration, LSP will also be enabled in your GPR buffer as well.  Then look for a Flymake error in this buffer and it should provide you the missing details.

With regards to your original question, the Eglot configuration just contains nested property lists for each "dotted" namespace.  Therefore, a `LIBRARY_TYPE` scenario variable (similar to what's shown at the top of [settings.md](https://github.com/AdaCore/ada_language_server/blob/master/doc/settings.md)) would be something like this along with the other settings in this workspace:

```elisp
((nil . ((lsp-ada-project-file . "src/gtkada.gpr")
	 (eglot-workspace-configuration . (:ada ( :projectFile "src/gtkada.gpr"
						  :scenarioVariables (:LIBRARY_TYPE "static"))))
         (compile-command . "alr build -- -cargs:ada -gnatef"))))
```

A very helpful way to check that you have this formatted correctly is to run `M-x eglot-show-workspace-configuration` from within your source file.  It will open a new buffer with the JSON representation and you should be able to tell if it's formatted correctly.

```json
{
  "ada": {
    "projectFile": "src/gtkada.gpr",
    "scenarioVariables": {
      "LIBRARY_TYPE": "static"
    }
  }
}
```

**Comment by mgrojo** [comment]
Thanks for all the information, it served to fix my issue, specially `M-x eglot-show-workspace-configuration`, since it wasn't loading the project file I thought.
